name: Keep looking forward
favicon: null
layout_spectrum: 1
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4ebe5'
    - '#536e8e'
    - '#040d17'
    - '#a6c9ba'
    - '#27435f'
  brandStrength: 0.5
  lightness: 0.05890300124883652
  saturation: 0.8868793540168554
  rhythmicContrast: 0.36933374684304
purpose: []
